THRILLERNAME=strictserial
STRICTSERIAL_SRC_NAMES=libstrictserial.cpp stricttracker.cpp 
STRICTSERIAL_HEADER_NAMES=libstrictserial.h stricttracker.h 
TARGET=libstrictserial.so
TESTFILES=libstrictserial.cpp
