THRILLERNAME=randomschedule
RANDOMSCHEDULE_SRC_NAMES=librandomschedule.cpp randomtracker.cpp
RANDOMSCHEDULE_HEADER_NAMES=librandomschedule.h randomtracker.h
TARGET=librandomschedule.so
TESTFILES=librandomschedule.cpp randomtracker.cpp


