THRILLERNAME=dpor
SRCS=libdpor.cpp dportracker.cpp ../racedetect/vctrack.cpp ../randomschedule/librandomschedule.cpp createhandler.cpp ../randomschedule/randomtracker.cpp ../serializer/libserializer.cpp ../serializer/executiontracker.cpp ../serializer/logger.cpp ../serializer/threadtracker.cpp
HEADERS=libdpor.h dportracker.h tlsdpor.h ../racedetect/vctrack.h ../racedetect/hybridtypes.h ../randomschedule/librandomschedule.h ../randomschedule/tlsrandomschedule.h ../randomschedule/randomtracker.h ../serializer/libserializer.h  ../serializer/tlsserializer.h  ../serializer/serializertypes.h  ../serializer/logger.h  ../serializer/executiontracker.h  ../serializer/threadtracker.h
TARGET=libdpor.so
TESTFILES=libdpor.cpp



include ../thrille-core/core.mk
